version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - "3000:3000"  
    environment:
      - NODE_ENV=development
    command: npm start  

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - "5000:5000"  
    environment:
      - NODE_ENV=development
    command: nodemon server.js  

  socket:
    build:
      context: ./socket
      dockerfile: Dockerfile
    volumes:
      - ./socket:/app
      - /app/node_modules
    ports:
      - "8080:8080"  
    environment:
      - NODE_ENV=development
    command: nodemon socket-server.js  
  mongodb:
    image: mongo:5.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"  

volumes:
  mongo-data:
