# service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-service-account
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-account
  namespace: default
